apiVersion: v1
kind: Service
metadata:
  name: node-red-scale-to-zero
  labels:
    app.kubernetes.io/name: node-red-scale-to-zero
    app.kubernetes.io/component: reference-example
spec:
  selector:
    app.kubernetes.io/name: node-red-scale-to-zero
  ports:
    - name: http
      port: 1880
      targetPort: http
