apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: node-red-http-settings
    files:
      - settings.js=config/settings.js
  - name: node-red-http-flows
    files:
      - flows.json=data/flows.json

generatorOptions:
  disableNameSuffixHash: true
