apiVersion: v1
kind: Service
metadata:
  name: node-red-http
  labels:
    app.kubernetes.io/name: node-red-http
    app.kubernetes.io/component: reference-example
spec:
  selector:
    app.kubernetes.io/name: node-red-http
  ports:
    - name: http
      port: 1880
      targetPort: http
